#include <iostream>
#include <windows.h>
#include <fstream>
#include <sstream>
#include <string>

// volume support 0.2.0

using namespace std;
string output="";

void clipfail() {
    cout<<"Cant open clipboard"<<endl;
    system("pause");
    exit(2);
}

void toClipboard(HWND hwnd, const std::string &s){
	if(!OpenClipboard(hwnd)) clipfail();
	EmptyClipboard();
	HGLOBAL hg=GlobalAlloc(GMEM_MOVEABLE,s.size()+1);
	if (!hg){
		CloseClipboard();
		return;
	}
	memcpy(GlobalLock(hg),s.c_str(),s.size()+1);
	GlobalUnlock(hg);
	SetClipboardData(CF_TEXT,hg);
	CloseClipboard();
	GlobalFree(hg);
}

int main()
{
    if(!OpenClipboard(NULL)) clipfail();
    HANDLE h;
    h = GetClipboardData(CF_TEXT);
    CloseClipboard();
    string clipboard = (char*)h;
    string format = clipboard.substr(0,19);
    if(format=="ModPlug Tracker  IT" || format=="ModPlug Tracker MPT") {

    } else {
    cout<<"Invalid data"<<endl;
    system("pause");
    return 1;
    }
    int sizee=0;
    int offset=0;


    while(1) {

   offset=offset+14;
    if(offset+22>clipboard.length()) break;
    sizee=sizee+1;
    }
    stringstream shxheader;
     shxheader << hex << sizee+1;
    string hxheader = shxheader.str();
    if(hxheader.length()==1) hxheader=hxheader+ "0";
    string hxheaderout;
    hxheaderout=hxheader.substr(1,1)+hxheader.substr(0,1);
     cout<<hxheaderout<<endl;
     output=hxheaderout;
     string tempstr;
     string fnote;
     string foct;
    string fvol="0";
     offset = 0;
     while(1) {
    tempstr = clipboard.substr(22+offset,8);
    cout<<tempstr<<endl;
    if(tempstr.substr(0,2)=="..") fnote = "0";
    if(tempstr.substr(0,2)=="==") fnote = "1";
    if(tempstr.substr(0,2)=="C-") fnote = "4";
    if(tempstr.substr(0,2)=="C#") fnote = "5";
    if(tempstr.substr(0,2)=="D-") fnote = "6";
    if(tempstr.substr(0,2)=="D#") fnote = "7";
    if(tempstr.substr(0,2)=="E-") fnote = "8";
    if(tempstr.substr(0,2)=="F-") fnote = "9";
    if(tempstr.substr(0,2)=="F#") fnote = "a";
    if(tempstr.substr(0,2)=="G-") fnote = "b";
    if(tempstr.substr(0,2)=="G#") fnote = "c";
    if(tempstr.substr(0,2)=="A-") fnote = "d";
    if(tempstr.substr(0,2)=="A#") fnote = "e";
    if(tempstr.substr(0,2)=="B-") fnote = "f";


    if(tempstr.substr(2,1)=="1") foct = "0";
    if(tempstr.substr(2,1)=="2") foct = "2";
    if(tempstr.substr(2,1)=="3") foct = "4";
    if(tempstr.substr(2,1)=="4") foct = "6";
    if(tempstr.substr(2,1)=="5") foct = "8";
    if(tempstr.substr(2,1)=="6") foct = "a";
    if(tempstr.substr(2,1)=="7") foct = "c";
    if(tempstr.substr(2,1)=="8") foct = "e";
    if(tempstr.substr(2,1)==".") foct = "0";
    if(tempstr.substr(2,1)==".") foct = "0";

  //  if(false) {
    if(tempstr.substr(5,1)=="v") {
        stringstream tempvolss(tempstr.substr(6,2));
        int tempvol=0;
        tempvolss >> tempvol;
        if(tempvol==0) fvol="f";
        if(tempvol>=1) fvol="e";
        if(tempvol>=4) fvol="d";
        if(tempvol>=8) fvol="c";
        if(tempvol>=12) fvol="b";
        if(tempvol>=16) fvol="a";
        if(tempvol>=20) fvol="9";
        if(tempvol>=24) fvol="8";
        if(tempvol>=28) fvol="7";
        if(tempvol>=32) fvol="6";
        if(tempvol>=38) fvol="5";
        if(tempvol>=42) fvol="4";
        if(tempvol>=46) fvol="3";
        if(tempvol>=50) fvol="2";
        if(tempvol>=54) fvol="1";
        if(tempvol>=60) fvol="0";
       cout<<"T: "<<tempvol<<" TO: "<<fvol<<" B: "<<tempstr.substr(6,2)<<endl;

    }//}

    output = output+ fnote+fvol+"000"+foct;
    offset=offset+14;
    if(offset+22>clipboard.length()) break;

    }

     ofstream myfile;
     myfile.open ("output.txt");
     myfile << "Generated by MPT-TO-TIC\n"+output;
     myfile.close();
     toClipboard(NULL,output);
    return 0;
}
